/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Shajib' at '9/4/15 3:00 PM' with Gradle 2.4
 *
 * @author Shajib, @date 9/4/15 3:00 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
